# Generated by Django 5.2.6 on 2025-09-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_news_promo_review_cart_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кофейни')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Кофейня',
                'verbose_name_plural': 'Кофейни',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID пользователя Telegram'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user_id', 'product')},
        ),
    ]
